const makeupProducts = [
  {
    typevideo: false,
    type: 'isProduct',
    bagde: 26.0,
    imgProduct: '../assets/images/makeup-pri-1.webp',
    secondaryProduct: '../assets/images/makeup-sec-1.webp',
    tags: ['Moisturizes', 'Nourrishes'],
    title: 'The Lip Trio',
    priceprev: 86,
    price: 60.0,
    desc: '',
    rating: '',
    review: '',
  },
  {
    typevideo: false,
    type: 'isProduct',
    bagde: 23.0,
    imgProduct: '../assets/images/makeup-pri-2.webp',
    secondaryProduct: '../assets/images/makeup-sec-2.webp',
    tags: [],
    title: 'The Smoky Eye Trio',
    priceprev: 86.0,
    price: 37.0,
    desc: 'The Trio for bold eyes...',
    rating: '',
    review: '',
  },
  {
    typevideo: false,
    type: 'isProduct',
    bagde: 'Best Seller',
    imgProduct: '../assets/images/makeup-pri-3.webp',
    secondaryProduct: '../assets/images/makeup-sec-3.webp',
    tags: ['Evens out', 'skin tone'],
    title: 'Le Multicorrecteur...',
    priceprev: '',
    price: 28.0,
    desc: 'Multipurpose concealer',
    rating: 4.4,
    review: 62,
  },
  {
    typevideo: true,
    type: 'isProduct',
    bagde: 'Best Seller',
    imgProduct: '../assets/images/makeup-pri-4.webp',
    secondaryProduct: '../assets/videos/makeup-sec-4.mp4',
    tags: ['Illuminates', 'Nourrishes', 'Protects'],
    title: 'Le Smoky Christophe Danchaud',
    priceprev: '',
    price: 23.0,
    desc: 'Eye shadow pencils with a (skincare) twist',
    rating: 4.5,
    review: 79,
  },
  {
    type: 'isProductCenter',
    typevideo: false,
    bagde: '',
    imgProduct: '../assets/images/makeup-center-1.webp',
    secondaryProduct: '',
    tags: [],
    title: 'On all orders over €100',
    priceprev: '',
    price: '',
    desc: 'Free international delivery',
    rating: 0,
    review: 0,
  },
  {
    typevideo: false,
    type: 'isProduct',
    bagde: '',
    imgProduct: '../assets/images/makeup-pri-5.webp',
    secondaryProduct: '../assets/images/makeup-sec-5.webp',
    tags: ['Illuminates', 'Moisturizes', 'Nourishes'],
    title: 'Le Lip Glow Christophe...',
    priceprev: '',
    price: 26.0,
    desc: 'Lip oil for natural, glossy-looking lips ',
    rating: 4.7,
    review: 59,
  },
  {
    typevideo: true,
    type: 'isProduct',
    bagde: 'Best Seller',
    imgProduct: '../assets/images/makeup-pri-6.webp',
    secondaryProduct: '../assets/videos/makeup-sec-6.mp4',
    tags: ['Matifies', 'Sets makeup'],
    title: 'La Poudre Christophe Danchaud',
    priceprev: '',
    price: 38.0,
    desc: 'Loose mineral powder, absolutely invisible on the skin...',
    rating: 4.6,
    review: 71,
  },
  {
    typevideo: false,
    type: 'isProduct',
    bagde: 'Best Seller',
    imgProduct: '../assets/images/makeup-pri-7.webp',
    secondaryProduct: '../assets/images/makeup-sec-7.webp',
    tags: ['Moisturizes', 'Nourishes'],
    title: 'Le Mat 11 Bois de Rose',
    priceprev: '',
    price: 30.0,
    desc: 'Vegan lipstick with a velvety finish',
    rating: 5.0,
    review: 2,
  },
  {
    typevideo: false,
    type: 'isProduct',
    bagde: '',
    imgProduct: '../assets/images/makeup-pri-8.webp',
    secondaryProduct: '../assets/images/makeup-sec-8.webp',
    tags: ['Moisturizes', 'Nourishes'],
    title: 'Le Mat 16 Coquelicot',
    priceprev: '',
    price: 30.0,
    desc: 'Vegan lipstick with a velvety finish',
    rating: 5.0,
    review: 1,
  },
  {
    typevideo: false,
    type: 'isProduct',
    bagde: 'Best Seller',
    imgProduct: '../assets/images/makeup-pri-9.webp',
    secondaryProduct: '../assets/images/makeup-sec-9.webp',
    tags: ['Moisturizes', 'Nourishes'],
    title: 'Le Mat 08 Théâtre',
    priceprev: '',
    price: 38.0,
    desc: 'Vegan lipstick with a velvety finish',
    rating: 5.0,
    review: 3,
  },
  {
    typevideo: false,
    type: 'isProductCenter',
    bagde: '',
    imgProduct: '../assets/images/makeup-center-2.webp',
    secondaryProduct: '',
    tags: [],
    title: 'Our organic makeup',
    priceprev: '',
    price: '',
    desc: 'Discover',
    rating: 0,
    review: 0,
  },
  {
    typevideo: false,
    type: 'isProduct',
    bagde: 'Best Seller',
    imgProduct: '../assets/images/makeup-pri-10.webp',
    secondaryProduct: '../assets/images/makeup-sec-10.webp',
    tags: ['Films', 'Smoothes'],
    title: 'La Crème du Temps',
    priceprev: '',
    price: 62.0,
    desc: 'Complete pro-aging moisturizer for mature skin ',
    rating: 4.7,
    review: 67,
  },
];

const productMakeUpList = document.querySelector('.product-makeup-list');
makeupProducts.forEach((item) => productMakeUpList.appendChild(Product(item)));
